ALL_TEXT = {
    "main_window_title": "FileMover",
    "menu": ("Sobre FileMover", "About"),
    "title": ("Bienvenido a FileMover!", "Welcome to FileMover!"),
    "app_desc": ("Para comenzar simplemente pegue las rutas correspondientes o busque las rutas presionando el botón",
                 "To get started just copy and paste the corresponding directories or just navigate trough them by pressing each button"),
    "prox_path": ("Ruta proxies:", "Proxies path:"),
    "raws_path": ("Ruta raws:", "Raws path:"),
    "dump_path": ("Ruta archivo dump:", "Dump file path:"),
    "nav_button": ("Buscar carpeta...", "Search folder..."),
    "ext_jps": ("Extensión proxies", "Proxies extension"),
    "ext_raw": ("Extensión raws", "Raws extension"),
    "raw_folder": ("Ej: myRawsMovidos", "e.g MyMovedRaws"),
    "donate_menu": ("Donar", "Donate"),
    "about_text": ("Gracias por usar FileMover, cualquier sugerencia o recomendación siéntase libre de contactarse conmigo a través de cualquiera de mis redes sociales. \nSi pudieras dejar una donación lo agradecería un montón y me motivaría a seguir creando software util gratis y libre.\n¿Quisiera visitar mi linktr? https://linktr.ee/GiovanniLDev", "Thanks for using FileMover, for any suggestions you might have, please feel free to reach out through any of my social media accounts.\nAlso if you could contribute by donating I would appreciate it and would motivate me to create more useful free open-source software.\nWould you like to visit my linktr? https://linktr.ee/GiovanniLDev"),
    "about_menu": "About",
    "button": "MoveRaws!",
    "warn_precopy_title": ("Atención!", "Warning!"),
    "warn_precopy_text": ("Esto puede tomar un tiempo, por favor espera hasta que el proceso termine. Si necesita interrumpirlo, no se preocupe, vuelva a ejecutar el programa y se retomará el proceso normalmente", "This might take a while, please wait until the process is finished, if you need to interrupt the process, don't worry, the next time you execute the program it will resume the copy normally."),
    "warn_copy_success_title": ("Éxito!", "Success!"),
    "raws_folder_chkb": ("Mover Raws a nueva carpeta?","Move raws into a new folder?"),
    "dump_file_chkb": ("Generar archivo dump con raws no encontrados?","Generate dump file containing all missing raws?"),
    "copy_chkb": ("Mantener copias raws originales?","Keep original raws copies?"),
    "linkedin_link": ("https://www.linkedin.com/in/giovannil-lombardi/?locale=es_ES","https://www.linkedin.com/in/giovannil-lombardi/"),
    "linktree_link": "https://linktr.ee/GiovanniLDev",
    "help_menu": ("Ayuda", "Help")
}
